#!/usr/bin/env sh

set -eu

cd -- "$(dirname -- "$0")"

if [ "$#" -eq 0 ]; then
    echo "Usage: ./launch [file-name] [--mint] [--network mainnet|devnet]"
    echo "Example: ./launch bonk.mp3"
    exit 1
fi

mkdir -p out

javac -d out $(find src -name "*.java")

java -cp out Main "$@"
